version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: social_network_db
      POSTGRES_USER: social_user
      POSTGRES_PASSWORD: social_password
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

volumes:
  pgdata:
